### ISSUE TITLE
Feedback zur Pflichtübung 1

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/repo-17#1]
## Paketname

Der Paketname ist eindeutig.

## JavaDoc

JavaDoc ist vorhanden. Allerdings fehlt die Beschreibung der Parameter. D.h. statt z.B.

```java
	/**
     * Konstruktor, einzige möglichkeit, Fläche festzulegen
     * 
     * @param flaeche
     */
```

sollte es heißen

```java
	/**
     * Konstruktor, einzige möglichkeit, Fläche festzulegen
     * 
     * @param flaeche die Flaeche der Figur in qm
     */	
```

Die Beschreibung der Klasse sitzt an der falschen Stelle. Statt

```java
/**
 * @author 1423444 Dient als Elternklasse für alle möglichen Figuren hat eine
 *         Fläche und gibt diese aus.
 */
```

müsste korrekterweise dort stehen

```java
/**
 * Dient als Elternklasse für alle möglichen Figuren hat eine
 * Fläche und gibt diese aus.
 *
 * @author 1423444 
 */
```

[-3 Punkte]

## Coding-Standard

Wurde weitgehend eingehalten.

## Figuren

Alles Ok.

## UML

  * Konstruktoren müssen unterstrichen werden.

## Bewertung

**97 Punkte**

**Bitte korrigieren Sie die genannten Fehler bis zur nächsten Übungsstunde, checken Sie die Verbesserung ein und schließen Sie dann dieses Issue.**

**Comment by 1423444** [comment]
### Issue resolved
###### Neues UML-Diagramm:
 Kontruktoren
- unterstrichen
- beinhalten Parameter mit Namen

###### Code verbessert:
JDoc Parameter
- beschrieben
- Klassenbeschreibung über @author
